### ISSUE TITLE
got an error in scraping reviews

### ISSUE THREAD

**Issue by siavashfrz** [AndreiChernovJr/British-Airways-customer-experience-review#1]
Hi Andrei, when I want to run the code I get this error:
NameError: name 'review_block' is not defined
it seems you didn't define the review_block. could you please recheck the code?/.
Thank you.

**Comment by AndreiChernovJr** [comment]
@siavashfrz Hi, Siavash! Thank you for reaching out and addressing the issue.
I was disappointed to learn that the scrapper doesn't work any more. I checked the website HTML code and discovered they changed the structure. Unfortunately for proper functioning the scrapper needs to be rewritten according to the new website structure.

**Comment by AndreiChernovJr** [comment]
If you scrap the website you will also be able to see that some information is now missing (like verification status).
I'm not going to rewrite the code completely since the project it was written for has finished long ago but you can still make use of the code provided if you combine it with new website code structure. 
Example below:

for review_block in soup.find_all("article", itemprop="review"):

    review_text = review_block.find("div", itemprop="reviewBody").get_text(strip=True)
    
    verification_status = "Verified" if review_block.find("a", href="https://www.airlinequality.com/verified-reviews/") else "Not Verified"
    
    rating_element = review_block.find("span", itemprop="ratingValue")
    if rating_element:
        rating = rating_element.get_text(strip=True)
    else:
        rating = None
    
    author = review_block.find("span", itemprop="name").get_text(strip=True)
    
    review_date_str = review_block.find("time", itemprop="datePublished")["datetime"]
    review_date = datetime.strptime(review_date_str, "%Y-%m-%d")
    
    df = df.append({
        "Review Text": review_text,
        "Verification Status": verification_status,
        "Rating": rating,
        "Author": author,
        "Review Date": review_date
    }, ignore_index=True)

print(df)
